add additional error reporting depiste euo pipefail

diff --git a/bin/puzzler b/bin/puzzler
--- a/bin/puzzler
+++ b/bin/puzzler
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 ########### EDIT THIS BLOCK WITH SLURM & APPTAINER/SINGULARITY SETTINGS ############
-#SBATCH --time=0-08:00:00   
+#SBATCH --time=0-24:00:00   
 #SBATCH --nodes=1  
-#SBATCH --ntasks-per-node=12
-#SBATCH --mem=64Gb
+#SBATCH --ntasks-per-node=64
+#SBATCH --mem=512Gb
 #SBATCH --partition=ceres
 #SBATCH --account=coffea_pangenome
 
@@ -129,6 +129,7 @@ echo -e "=======================================================================
 set -euo pipefail
 $PUZZLER hifiasm --version > /dev/null 2>&1 || { -e "\e[40m~~~~ hifiasm not found, is runtime set and container exists? ~~~~\e[0m"; exit 1; } 
 $PUZZLER haphic --version > /dev/null 2>&1 || { -e "\e[40m~~~~ haphic not found, is runtime set and container exists? ~~~~\e[0m"; exit 1; } 
+trap 'echo -e "\n❌ \e[41mCommand failed:\e[0m \"$BASH_COMMAND\" (line $LINENO)\n" >&2' ERR
 
 ########## End checks #############
 
@@ -363,7 +364,7 @@ else
 
     ##### Extract post juicebox assembly
     if [ "$NO_JUICE" = "TRUE" ]; then
-        echo -e "\e[41m~~~~ Skipping juicer extraction for ${SAMPLE}, --no_juice requested! (not recommended!) ~~~~\e[0m"
+        echo -e "\e[42m~~~~ Skipping juicer extraction for ${SAMPLE}, --no_juice requested! (not recommended!) ~~~~\e[0m"
     elif [ ! -s "${WD}/juicer_files/${SAMPLE}_JBAT.review.assembly" ]; then
         echo -e "\e[41m~~~~ Post curation assembly file missing for ${SAMPLE}: Run Juicebox & place in ${WD}/juicer_files/${SAMPLE}_JBAT.review.assembly ~~~~\e[0m"
         exit 1 
@@ -405,21 +406,22 @@ else
             echo -e "\e[41m~~~~ Skipping draft-reference mapping for ${SAMPLE}, missing input: ${WD}/${SAMPLE}/05_postjuicebox/post_juicer_asm.fa ~~~~\e[0m"
         else
 
-            # If genome is massive, reduce minimap2 options
-            MINIMAP_CMD="${PUZZLER} minimap2 -x asm5 ${REFERENCE} post_juicer_asm.fa --secondary=no -t ${t} -o asmpost_to_paf.paf 2> ${SAMPLE}.minimap.postjuicer.log"
-            GENOME_SIZE=$(wc -c < "post_juicer_asm.fa")
-            GENOME_SIZE_GB=$((GENOME_SIZE / 1000000000))
+            # # If genome is massive, reduce minimap2 options
+            # MINIMAP_CMD="${PUZZLER} minimap2 -x asm5 ${REFERENCE} post_juicer_asm.fa --secondary=no -t ${t} -o asmpost_to_paf.paf 2> ${SAMPLE}.minimap.postjuicer.log"
+            # GENOME_SIZE=$(wc -c < "post_juicer_asm.fa")
+            # GENOME_SIZE_GB=$((GENOME_SIZE / 1000000000))
 
-            # Check if genome is larger than 3GB and add -n10 if needed
-            if [ "$GENOME_SIZE_GB" -gt 3 ]; then
-                MINIMAP_CMD="${PUZZLER} minimap2 -x asm5 -n10 -k21 -w19 ${REFERENCE} post_juicer_asm.fa --secondary=no -t ${t} -o asmpost_to_paf.paf 2> ${SAMPLE}.minimap.postjuicer.log"
-                echo -e "\e[43m~~~~ Genome size is ${GENOME_SIZE_GB}GB, adding -n10 -k21 -w19 to minimap2 command ~~~~\e[0m"
-            else
-                echo -e "\e[43m~~~~ Genome size is ${GENOME_SIZE_GB}GB, running default minimap2 command ~~~~\e[0m"
-            fi
+            # # Check if genome is larger than 3GB and add -n10 if needed
+            # if [ "$GENOME_SIZE_GB" -gt 3 ]; then
+            #     MINIMAP_CMD="${PUZZLER} minimap2 -x asm5 -n10 -k21 -w19 ${REFERENCE} post_juicer_asm.fa --secondary=no -t ${t} -o asmpost_to_paf.paf 2> ${SAMPLE}.minimap.postjuicer.log"
+            #     echo -e "\e[43m~~~~ Genome size is ${GENOME_SIZE_GB}GB, adding -n10 -k21 -w19 to minimap2 command ~~~~\e[0m"
+            # else
+            #     echo -e "\e[43m~~~~ Genome size is ${GENOME_SIZE_GB}GB, running default minimap2 command ~~~~\e[0m"
+            # fi
 
             # Run Minimap2
-            eval "$MINIMAP_CMD"
+            ${PUZZLER} minimap2 -x asm20 ${REFERENCE} post_juicer_asm.fa --secondary=no -t ${t} -o asmpost_to_paf.paf 2> ${SAMPLE}.minimap.postjuicer.log
+            #eval "$MINIMAP_CMD"
 
             # Renaming: to reference chromosomes 
             ${PUZZLER} samtools faidx post_juicer_asm.fa
@@ -670,106 +672,6 @@ else
         echo -e "\e[42m~~~~ Skipping NCBI taxdump, ${BLOB_DB}/data/nodes.dmp exists ~~~~\e[0m"
     fi 
 
-    # #### Download uniprot databases (MASSIVE!)     
-    # UP_LOCK_FILE="${BLOB_DB}/download_up.lock"
-
-    # # Capture output and errors
-    # if [ -f "$UP_LOCK_FILE" ]; then
-    #     echo -e "\e[41m~~~~ Another instance already dl-ing uniprot db. Resubmit puzzler when finished or rm $UP_LOCK_FILE! Exiting ~~~~\e[0m"
-    #     exit 1
-    # elif [ ! -f "$UP_LOCK_FILE" ] && [ ! -s "${BLOB_DB}/uniprot/reference_proteomes.dmnd" ] && [ ! -f "${BLOB_DB}/uniprot_db.complete" ]; then
-    #     echo -e "\e[43m~~~~ Checking/Downloading uniprot database.... will take hours if non-existent ~~~~\e[0m"
-    #     touch "$UP_LOCK_FILE"
-
-    #     mkdir -p ${BLOB_DB}/uniprot
-    #     cd ${BLOB_DB}/
-
-    #     {
-    #     wget -q -O uniprot/reference_proteomes.tar.gz \
-    #     ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/$(curl \
-    #         -vs ftp.ebi.ac.uk/pub/databases/uniprot/current_release/knowledgebase/reference_proteomes/ 2>&1 | \
-    #         awk '/tar.gz/ {print $9}')
-    #     cd uniprot
-    #     tar xf reference_proteomes.tar.gz
-
-    #     touch reference_proteomes.fasta.gz
-    #     find . -mindepth 2 | grep "fasta.gz" | grep -v 'DNA' | grep -v 'additional' | xargs cat >> reference_proteomes.fasta.gz
-
-    #     echo -e "accession\taccession.version\ttaxid\tgi" > reference_proteomes.taxid_map
-    #     zcat */*/*.idmapping.gz | grep "NCBI_TaxID" | awk '{print $1 "\t" $1 "\t" $3 "\t" 0}' >> reference_proteomes.taxid_map
-
-    #     echo -e "\e[43m~~~~ Creating diamond uniprot reference proteome database.... ~~~~\e[0m"
-    #     ${PUZZLER} diamond makedb -p ${t} --in reference_proteomes.fasta.gz --taxonmap reference_proteomes.taxid_map --taxonnodes ${BLOB_DB}/data/nodes.dmp -d reference_proteomes.dmnd
-    #     } > ${BLOB_DB}/uniprot_db.log 2>&1
-    #     # Database is ready, so remove the lock file 
-    #     echo -e "\e[43m~~~~ Uniprot database created successfully successfully ~~~~\e[0m"
-    #     touch ${BLOB_DB}/uniprot_db.complete
-    #     rm "$UP_LOCK_FILE"
-    # else
-    #     echo -e "\e[42m~~~~ Error detected during uniprot database creation! Check ${BLOB_DB}/uniprot or rm $UP_LOCK_FILE ~~~~\e[0m"
-    # fi 
-
-    # cd ${WD}/${SAMPLE}/07_busco_yak_blob
-    # if [ -s "${WD}/${SAMPLE}/07_busco_yak_blob/diamond_1mb.out" ] && [ -f "${WD}/${SAMPLE}/blastx.complete" ]; then
-    #         echo -e "\e[42m~~~~ Skipping blastx, ${WD}/${SAMPLE}/07_busco_yak_blob/diamond_1mb.out exists ~~~~\e[0m"
-    # else
-    #     {
-    #     # Split primary assembly into 1Mb sliding windows
-    #     ${PUZZLER} seqkit sliding -s 1000000 -W 1000000 -g \
-    #         -o primary_split_1mb.fa "${WD}/primary_asm/${SAMPLE}.fa"
-    #     ${PUZZLER} seqkit split --by-size 1 primary_split_1mb.fa -O blast_parts_1mb
-
-    #     # Run BLAST on each chunk in parallel
-    #     for f in blast_parts_1mb/*.fa; do
-    #         ${PUZZLER} diamond blastx \
-    #             --query "$f" \
-    #             --db ${BLOB_DB}/uniprot/reference_proteomes.dmnd \
-    #             --outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore \
-    #             --sensitive \
-    #             --max-target-seqs 1 \
-    #             --evalue 1e-25 \
-    #             --threads ${t} \
-    #             > "$f.dmnd.out"
-    #     done
-
-    #     # Combine results
-    #     cat blast_parts_1mb/*.dmnd.out > "${WD}/${SAMPLE}/07_busco_yak_blob/diamond_1mb.out"
-    #     } > blastx.log 2>&1
-    #     touch ${WD}/${SAMPLE}/blastx.complete
-    # fi 
-
-    # cd ${WD}/${SAMPLE}/07_busco_yak_blob
-    # if [ ! -s "diamond_1mb.out" ] && [ ! -s "${WD}/${SAMPLE}/blastx.complete" ]; then
-    #     echo -e "\e[41m~~~~ Blast file is empty for ${SAMPLE}, check ${WD}/${SAMPLE}/07_busco_yak_blob/blastx.log ~~~~\e[0m"
-    #     exit 1 
-    # elif [ ! -s "${WD}/${SAMPLE}/06_realign_hic_hifi/asm.hifi.bam" ]; then
-	#      echo -e "\e[41m~~~~ Alignment file missing for ${SAMPLE}, check ${WD}/${SAMPLE}/06_realign_hic_hifi/asm.hifi.bam ~~~~\e[0m"
-    # elif [ -s "${BLOB_DB}/data/nodesDB.txt" ]; then
-
-    #     echo -e "\e[43m~~~~ Creating blobplot for ${SAMPLE} ~~~~\e[0m"  
-    #     { ${PUZZLER} blobtools create -i ${WD}/primary_asm/${SAMPLE}.fa -b ${WD}/${SAMPLE}/06_realign_hic_hifi/asm.hifi.bam -t diamond_1mb.out \
-    #         --db ${BLOB_DB}/data/nodesDB.txt -o ${SAMPLE} && \
-    #         ${PUZZLER} blobtools view -i ${SAMPLE}.blobDB.json && \
-    #         ${PUZZLER} blobtools plot -i ${SAMPLE}.blobDB.json --format pdf; } > blob.log 2>&1
-    #     cp ${SAMPLE}*blobplot.bam0.pdf ${WD}/primary_asm/stats/${SAMPLE}.blob.pdf
-    #     cp ${SAMPLE}.*blobplot.stats.txt ${WD}/primary_asm/stats/${SAMPLE}.blob.stats.txt
-    #     cp ${SAMPLE}.*table.txt ${WD}/primary_asm/stats/${SAMPLE}.blob.contaminants.txt
-
-    # elif [ ! -s "${BLOB_DB}/data/nodesDB.txt" ]; then 
-
-    #     echo -e "\e[43m~~~~ Creating blobplot for ${SAMPLE} ~~~~\e[0m"
-    #     { ${PUZZLER} blobtools create -i ${WD}/primary_asm/${SAMPLE}.fa -b ${WD}/${SAMPLE}/06_realign_hic_hifi/asm.hifi.bam -t diamond_1mb.out \
-    #         --nodes ${BLOB_DB}/data/nodes.dmp --names ${BLOB_DB}/data/names.dmp --db ${BLOB_DB}/data/nodesDB.txt -o ${SAMPLE} && \
-    #         ${PUZZLER} blobtools view -i ${SAMPLE}.blobDB.json && \
-    #         ${PUZZLER} blobtools plot -i ${SAMPLE}.blobDB.json --format pdf; } > blob.log 2>&1
-    #     cp ${SAMPLE}*blobplot.bam0.pdf ${WD}/primary_asm/stats/${SAMPLE}.blob.pdf
-    #     cp ${SAMPLE}.*blobplot.stats.txt ${WD}/primary_asm/stats/${SAMPLE}.blob.stats.txt
-    #     cp ${SAMPLE}.*table.txt ${WD}/primary_asm/stats/${SAMPLE}.blob.contaminants.txt
-
-    # else
-    #     echo -e "\e[42m~~~~ Skipping blobtools, ${BLOB_DB}/data/nodesDB.txt is missing ~~~~\e[0m"
-    # fi 
-
     #### Download refseq nt databases (MASSIVE!) 
     mkdir -p ${BLOB_DB}/nt
     cd ${BLOB_DB}/nt
@@ -806,32 +708,6 @@ else
             echo -e "\e[42m~~~~ Skipping blast, ${WD}/${SAMPLE}/07_busco_yak_blob/blast.out exists ~~~~\e[0m"
     else
         echo -e "\e[43m~~~~ Blasting ${SAMPLE} against nt... will take hours and huge RAM ~~~~\e[0m"
-        # mkdir -p ${WD}/${SAMPLE}/07_busco_yak_blob/blast_parts
-        # cd ${WD}/${SAMPLE}/07_busco_yak_blob/blast_parts
-
-        # # Split primary assembly into 1Mb sliding windows
-        # ${PUZZLER} seqkit sliding -s 1000000 -W 1000000 -g \
-        #     -o primary_split_1mb.fa "${WD}/primary_asm/${SAMPLE}.fa"
-
-        # # Split the resulting FASTA file into ~smaller multi-seq parts for parallel BLAST
-        # ${PUZZLER} split -a 3 -f primary_split_1mb.fa --output-prefix query_chunk_
-
-        # # Run BLAST on each chunk in parallel
-        # for f in query_chunk_*; do
-        #     ${PUZZLER} blastn -db "${BLOB_DB}/nt/nt" \
-        #         -query "$f" \
-        #         -outfmt "6 qseqid staxids bitscore std" \
-        #         -max_target_seqs 10 \
-        #         -max_hsps 1 \
-        #         -evalue 1e-25 \
-        #         -num_threads "${t}" \
-        #         -out "$f.out" &
-        # done
-        # wait
-
-        # # Combine results
-        # cat query_chunk_*.out > "${WD}/${SAMPLE}/07_busco_yak_blob/blast.out"
-
         ${PUZZLER} blastn -task megablast \
             -db ${BLOB_DB}/nt/nt \
             -query ${WD}/primary_asm/${SAMPLE}.fa \
